# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Domain-TLD
version:      1.64
version_from: lib/Net/Domain/TLD.pm
installdirs:  site
requires:
    Carp:                          0
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
